#!/bin/bash

unset YARN_VERSION YARN_DOWNLOAD_PREFIX YARN_DOWNLOAD_MID YARN_DOWNLOAD_SUFFIX \
    YARN_SHASUM_EXT YARN_INSTALL_BASE_DIR YARN_INSTALL_DIR YARN_TAR_FLAGS

echo "Starting app..."

yarn start